version: "3.7"
x-setup:
  pgenv: &pgenv
    POSTGRES_PASSWORD: SECRET
    POSTGRES_DB: db
    POSTGRES_USER: someuser
    # to force user/password:
    # PASSWORD: secret
  myenv: &myenv
    MYSQL_USER: someuser
    MYSQL_DATABASE: db
    MYSQL_ROOT_PASSWORD: SECRET
    MYSQL_PASSWORD: SECRET
services:
  mysql:
    environment:
      <<: [ *myenv ]
    image: corpusops/mysql:5
  mymysql_dbbackup:
    volumes: ["db-backup:/srv/backups"]
    image: corpusops/dbsmartbackup:mysql-5
    environment:
      <<: [ *myenv ]
      HOST: "mysql"
      DBNAMES: "db"
      # BACKUP_TYPE: "mysql"
      # DBS_PERIODICITY: "0 3 * * *"
      # user launching command
      # DBS_USER: "root"
      # DBS_COMMAND: "/usr/local/bin/run_dbsmartbackup.sh --quiet --no-colors"
      # to save all databases
      # DBNAMES: "all"
      # DBUSER: "superman"
      # PORT: "3306"
      # KEEP_LASTS: "1"
      # KEEP_DAYS: "2"
      # KEEP_WEEKS: "0"
      # KEEP_MONTHES: "0"
      # KEEP_LOGS: "7"
      # RUNAS: "foobar"
  pgsql:
    environment:
      <<: [ *pgenv ]
    image: corpusops/postgres:10
  mypostgresql_dbbackup:
    volumes: ["db-backup:/srv/backups"]
    image: corpusops/dbsmartbackup:postgres-10
    environment:
      <<: [ *pgenv ]
      HOST: "pgsql"
      DBNAMES: "db"
volumes:
  db-backup:
